### PR TITLE
Replace net-tools with iproute2

### PR DESCRIPTION
**Pull request by melon3r**
Replaced `arp` and `nestat` from `net-tools` package, which are deprecated, by `ip` commands from the newer package `iproute2`.

### CODE REVIEW

**Comment by melon3r** [comment]
Didn't take macOS into account. Could follow #23 and update only the Linux part.

**Comment by evilsocket** [comment]
As long as this breaks others platforms compatibility and can't merge.

**Comment by melon3r** [comment]
Fixed it to work on macOS. I don't have a mac to test it though. @onura, could you test if your changes from #23 still work?

**Comment by onura** [comment]
Hi @melon3r ,

I think Go doesn't recognize the _unix postfix and compiles the file anyway. This cause the following error

github.com/evilsocket/bettercap-ng/net
net/net_unix.go:6:5: IPv4RouteParser redeclared in this block
	previous declaration at net/net_darwin.go:7:5
net/net_unix.go:7:5: IPv4RouteTokens redeclared in this block
	previous declaration at net/net_darwin.go:8:5
net/net_unix.go:8:5: IPv4RouteCmd redeclared in this block
	previous declaration at net/net_darwin.go:9:5
net/net_unix.go:9:5: IPv4RouteCmdOpts redeclared in this block
	previous declaration at net/net_darwin.go:10:5
net/net_unix.go:11:112: IPv4RouteIsGateway redeclared in this block
	previous declaration at net/net_darwin.go:12:112
make: *** [build] Error 2

I managed to build it by ignoring net_unix.go file. However the value of NewEndpoint created at line 87 in net.go
`return NewEndpoint(gateway, mac), nil`
 can be read inside the IPv4RouteIsGateway

```
			return IPv4RouteIsGateway(iface.Name(), m, func(gateway string) (*Endpoint, error) {
				if gateway == iface.IpAddress {
					return iface, nil
				} else {
					// we have the address, now we need its mac
					mac, err := ArpLookup(iface.Name(), gateway, false)
					if err != nil {
						fmt.Printf("%s\n", err)
					}
					return NewEndpoint(gateway, mac), nil
				}
			})
```
but IPv4RouteIsGateway returns nil, nil. 

This is weird considering it works on Linux and I don't know why. Any idea?

**Comment by melon3r** [comment]
Thank you @onura.

I didn't realize _unix means both linux and macOS, so I renamed it to _linux and now it should build correctly.

`IPv4RouteIsGateway` was returning `nil, nil` because it was missing a `return` when calling `f`, which is now fixed.

**Comment by evilsocket** [comment]
guys let me just tell you the amazing work you're doing, and the project is not event 1.0.0 yet! thanks <3

**Comment by melon3r** [comment]
Great! Ready to merge if it looks good to you @evilsocket

**Comment by evilsocket** [comment]
So I just verified and it's working on both platforms, the only problem ( issue #10 ) I see on OS X is that packet forwarding does not work properly (now I can spoof targets and I see their traffic, but my computer does not forward packets correctly so the whole network is down). Anyone can test on OSX ( `firewall/firewall_darwin.go` handles this stuff on OSX ) and see why this happens?

**Pull request merged**
